from models.models_2d.CPFNet import CPFNet
from models.models_2d.DANet import DANet
from models.models_2d.DeepLabV3 import DeepLabV3
from models.models_2d.PSPNet import PSPNet
from models.models_2d.SegNet import SegNet
from models.models_2d.SwinUNet import SwinUNet
from models.models_2d.TransUNet import TransUNet
from models.models_2d.UNet import UNet
from models.models_2d.DefEDNet import DefEDNet
from models.models_2d.MedNeXt import MedNeXt
